### ISSUE TITLE
namespace and module is not good enough.

### ISSUE THREAD

**Issue by lygstate** [scross99/locic#6]
NodeJS's require is very good.

**Comment by scross99** [comment]
Hello,

>  namespace and module is not good enough.

Could you expand on this? What aspect do you think needs to be improved?

> NodeJS's require is very good.

I looked at NodeJS's require but it wasn't clear how this is relevant to Loci. Could you explain which aspects of NodeJS's require you think should be part of Loci?

Thanks,
Stephen

**Comment by lygstate** [comment]
nodejs's namespace encapsulation is very good
For example a1.0 depends on b2.0, and b2.0 depends on a0.5(Of cause a0.5 won't depends on b2.0,), and that would works
because of nodejs's require is just a function and encapsulate all
required things into a closure and won't be accessed outside.

**Comment by scross99** [comment]
> nodejs's namespace encapsulation is very good

Naturally I'd say Loci's module encapsulation is very good, but I'm biased :-). Are there particular aspects of NodeJS that you think are missing from Loci?

> For example a1.0 depends on b2.0, and b2.0 depends on a0.5(Of cause a0.5 won't depends on b2.0,), and that would works

Yes, dependencies of modules is something that will be established explicitly very soon in Loci; you can already build these structures but it's better for the dependency to be explicit and it also resolves ambiguities. The proposed syntax is:

```
import my.module 1.2.3 {
    import other.module 4.5.6;
    // ...
}
```

And similarly (when exporting):

```
export my.module 1.2.3 {
    import other.module 4.5.6;
    // ...
}
```

> because of nodejs's require is just a function and encapsulate all required things into a closure and won't be accessed outside.

Loci modules are extremely effective at encapsulation like this. You put your implementation in the source file and the 'header' files only expose the API. This means you can have lots of functions/classes/datatypes/structs defined internally to the module which aren't exposed to the outside world.

**Comment by lygstate** [comment]
2015-07-08 6:53 GMT+08:00 Stephen Cross <notifications@github.com>:

> nodejs's namespace encapsulation is very good
>
> Naturally I'd say Loci's module encapsulation is very good, but I'm biased
> :-). Are there particular aspects of NodeJS that you think are missing from
> Loci?
>
> For example a1.0 depends on b2.0, and b2.0 depends on a0.5(Of cause a0.5
> won't depends on b2.0,), and that would works
>
> Yes, dependencies of modules is something that will be established
> explicitly very soon in Loci; you can already build these structures but
> it's better for the dependency to be explicit and it also resolves
> ambiguities. The proposed syntax is:
>
> import my.module 1.2.3 {
>     import other.module 4.5.6;
>     // ...
> }
>
> And similarly (when exporting):
>
> export my.module 1.2.3 {
>     import other.module 4.5.6;
>     // ...
> }
>
>  because of nodejs's require is just a function and encapsulate all
> required things into a closure and won't be accessed outside.
>
> Loci modules are extremely effective at encapsulation like this. You put
> your implementation in the source file and the 'header' files only expose
> the API. This means you can have lots of
> functions/classes/datatypes/structs defined internally to the module which
> aren't exposed to the outside world.
>
I means define the version number in source code is not good to maintain
package dependencies.
The NodeJs have the package manager npm and that would well, and good to
handling package dependencies.
I think loci can also do similar things.


I see a lot of namespace things like C++ in loci stdlib code like namespace
a { namespace b { namespace c
would this be gone?

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scross99/locic/issues/6#issuecomment-119366694>.
>



-- 
         此致
礼
罗勇刚
Yours
    sincerely,
Yonggang Luo

**Comment by lygstate** [comment]
You may have a look at npmjs.org, that may inspire you.
In source code we do not need complicated export schema, we just export what we want, and using 
package.json to decide which package we depends on and use it.
Cause we can use something like npm, lpm maybe? to downloading dependencies packages, that's the most important part.
we do not specify the package version number inside source code, but in configuration file. and exports what we want.

**Comment by scross99** [comment]
> I means define the version number in source code is not good to maintain package dependencies. The NodeJs have the package manager npm and that would well, and good to handling package dependencies. I think loci can also do similar things.

Sure, it's possible to create packages from Loci modules but this would be a layer on top of the modules (e.g. as you suggest, create some sort of package.json that provides all the necessary information - some of this could probably be extracted from the source code). However I do expect that in most use-cases Loci developers will produce packages for an existing package manager.

The source level import/export specifiers are designed to be a reliable mechanism for creating stable versioned APIs. They also make it simple to export multiple API versions for a particular module, writing code such as:

```
export my.module 1.0.0 {
    // ...
}

export my.module 1.1.0 {
    // ...
}
```

Ultimately we need the `export` specifiers in source code to know which things are being exported. Furthermore we need the version numbers in source code so we can know which things are being exported for each API version. This is similarly true for `import`. So we do need to have this stuff in the source code.

> I see a lot of namespace things like C++ in loci stdlib code like namespace a { namespace b { namespace c
> would this be gone?

Namespaces are a key Loci feature; they're not going anywhere :-). You can use namespaces in `import`/`export` as well as outside them.
